import React from "react";
import { appColors } from "app/theme";

export const GridIcon = () => {
  return (
    <svg
      width="20"
      height="18"
      viewBox="0 0 20 18"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="0.200195"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="7.40039"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="14.6006"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="0.200195"
        y="6.2998"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="7.40039"
        y="6.2998"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="14.6006"
        y="6.2998"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="0.200195"
        y="12.6001"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="7.40039"
        y="12.6001"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
      <rect
        x="14.6006"
        y="12.6001"
        width="5.4"
        height="5.4"
        rx="1"
        fill={appColors.COMMON.SECONDARY_COLOR_13}
      />
    </svg>
  );
};
