import { Serie } from "@nivo/scatterplot";

export interface EligibilityScatterplotDataItemModel {
  x: number;
  y: string;
  incomeLevel: number;
  diseaseBurden: number;
  allocationCycleName?: string | null;
  eligibility: "Eligible" | "Not Eligible" | "Transition Funding";
}

export interface EligibilityScatterplotDataModel extends Serie {
  data: EligibilityScatterplotDataItemModel[];
}

export interface EligibilityScatterplotHoveredNode
  extends EligibilityScatterplotDataItemModel {
  yPosition: number;
  xPosition: number;
}

export const mockdata: EligibilityScatterplotDataModel[] = [
  {
    id: " ",
    data: [
      {
        x: 2002,
        diseaseBurden: 0,
        incomeLevel: 0,
        eligibility: "Not Eligible",
        y: " ",
      },
    ],
  },
  {
    id: "HIV",
    data: [
      {
        x: 2003,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2004,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2005,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2006,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2007,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2008,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2009,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2010,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2011,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2012,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2013,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: null,
      },
      {
        x: 2014,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2014-16",
      },
      {
        x: 2015,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2014-16",
      },
      {
        x: 2016,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2014-16",
      },
      {
        x: 2017,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2017-19",
      },
      {
        x: 2018,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2017-19",
      },
      {
        x: 2019,
        diseaseBurden: 3,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2017-19",
      },
      {
        x: 2020,
        diseaseBurden: 3,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2020-22",
      },
      {
        x: 2021,
        diseaseBurden: 3,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "HIV",
        allocationCycleName: "2020-22",
      },
    ],
  },
  {
    id: "Malaria",
    data: [
      {
        x: 2003,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2004,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2005,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2006,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2007,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2008,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2009,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2010,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2011,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2012,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2013,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: null,
      },
      {
        x: 2014,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2014-16",
      },
      {
        x: 2015,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2014-16",
      },
      {
        x: 2016,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2014-16",
      },
      {
        x: 2017,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2017-19",
      },
      {
        x: 2018,
        diseaseBurden: 2,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2017-19",
      },
      {
        x: 2019,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2017-19",
      },
      {
        x: 2020,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2020-22",
      },
      {
        x: 2021,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Malaria",
        allocationCycleName: "2020-22",
      },
    ],
  },
  {
    id: "RSSH",
    data: [
      {
        x: 2003,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2004,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2005,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2006,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2007,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2008,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2009,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2010,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2011,
        diseaseBurden: 0,
        eligibility: "Transition Funding",
        incomeLevel: 1,
        y: "RSSH",
        allocationCycleName: null,
      },
      {
        x: 2012,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2013,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "RSSH",
        allocationCycleName: null,
      },
      {
        x: 2014,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "RSSH",
        allocationCycleName: "2014-16",
      },
      {
        x: 2015,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "RSSH",
        allocationCycleName: "2014-16",
      },
      {
        x: 2016,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "RSSH",
        allocationCycleName: "2014-16",
      },
      {
        x: 2017,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2018,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2019,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2020,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
      {
        x: 2021,
        diseaseBurden: 0,
        incomeLevel: -1,
        eligibility: "Not Eligible",
        y: "RSSH",
      },
    ],
  },
  {
    id: "Tuberculosis",
    data: [
      {
        x: 2003,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2004,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2005,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2006,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2007,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2008,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2009,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2010,
        diseaseBurden: 0,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2011,
        diseaseBurden: 5,
        eligibility: "Not Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2012,
        diseaseBurden: 5,
        eligibility: "Not Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2013,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: null,
      },
      {
        x: 2014,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2014-16",
      },
      {
        x: 2015,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2014-16",
      },
      {
        x: 2016,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2014-16",
      },
      {
        x: 2017,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2017-19",
      },
      {
        x: 2018,
        diseaseBurden: 5,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2017-19",
      },
      {
        x: 2019,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2017-19",
      },
      {
        x: 2020,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2020-22",
      },
      {
        x: 2021,
        diseaseBurden: 4,
        eligibility: "Eligible",
        incomeLevel: 1,
        y: "Tuberculosis",
        allocationCycleName: "2020-22",
      },
    ],
  },
  {
    id: "",
    data: [
      {
        x: 2002,
        diseaseBurden: 0,
        incomeLevel: 0,
        eligibility: "Not Eligible",
        y: "",
      },
    ],
  },
];

export const diseaseBurdens = [
  "None",
  "Low",
  "Moderate",
  "Not High",
  "High",
  "Severe",
  "Extreme",
];

export const incomeLevels = [
  "None",
  "Low income",
  "Lower-Lower middle income",
  "Lower middle income",
  "Upper-Lower middle income",
  "Upper middle income",
  "High income",
];
